Open-Attestation/open-attestation

- .travis.yml
- package-lock.json
- package.json
- src/serialize/flatten.js
- test/e2e.test.js
using require() in flatten was causing rollup to fail silently
> changed flatten to es6

- package-lock.json
- package.json
- src/digest/digest.ts
- src/signature/merkle/merkle.test.ts
- src/signature/signature.ts
- src/utils/utils.test.ts
- src/utils/utils.ts
- remove crypto
- replace ethereum-utils by js-sha3
- remove sha256 and randomSalt from the lib (so it's a breaking change ...)
Any idea how to improve merkle.test.ts ? test need to call toBuffer implementation, however calling toBuffer doesnt work
> feat: use js-sha

- src/schema/2.0/schema.json
- src/schema/2.0/schema.test.ts
- test/e2e.v2.test.ts
- test/e2e.v3.test.ts
> fix: #68 - allow extra properties for v2 issuers

- src/index.ts
- src/privacy/privacy.test.ts
- src/privacy/privacy.ts
- src/schema/3.0/w3c.ts
- src/schema/schema.ts
- src/utils/utils.test.ts
- src/utils/utils.ts
moved getData because of cycle problem
fix #72
> feat: add getIssuerAddress helper

- src/schema/2.0/schema.json
- src/schema/2.0/schema.test.ts
> feat: add mimetypes

- src/digest/digest.ts
- test/e2e.v2.test.ts
- This reverts commit a0c783ff399f0d8a3390dcf6173c4287a051082d.
> feat: revert empty fields

- jest.config.js
- src/2.0/__tests__/obfuscate.test.ts
- src/3.0/__tests__/obfuscate.test.ts
- src/shared/utils/utils.ts
- test/fixtures/v2/not-obfuscated-wrapped.json
- test/fixtures/v2/obfuscated-wrapped.json
- test/fixtures/v3/not-obfuscated-wrapped.json
- test/fixtures/v3/obfuscated-wrapped.json
- shifting util from oa-verify https://github.com/Open-Attestation/oa-verify/pull/166 to here
> feat: util get obfuscated

- package-lock.json
- package.json
- Update Jsonld package to v4 to fix a security issue in one of the dependencies.
> fix: jsonld security issue

- src/index.ts
- export did signer as it was moved into oa but not exported.
> fix: export signer

- .circleci/config.yml
> fix: circleci-context

- package-lock.json
- package.json
- src/3.0/validate/validate.ts
node-fetch is all broken on browser https://github.com/node-fetch/node-fetch/pull/698. they recommend to use cross-fetch for browser support
> fix: change node-fetch to cross-fetch

- src/shared/utils/__tests__/utils.test.ts
- src/shared/utils/utils.ts
- test/fixtures/v2/raw-document.json
Update:  util to return unwrapped document data
> feat: add utils to extract v2/v3 template data

- src/2.0/schema/schema.json
- src/3.0/schema/schema.json
Add chain Details into oa schema v2 and v3
> feat: add chainDetail optional field into schema

- src/shared/utils/__tests__/utils.test.ts
- src/shared/utils/utils.ts
- test/fixtures/v2/did-form.json
- test/fixtures/v2/dns-did-form.json
- test/fixtures/v2/transferable-record-form.json
- test/fixtures/v2/verifiable-document-form.json
- test/fixtures/v3/did-form.json
- test/fixtures/v3/dns-did-form.json
- test/fixtures/v3/transferable-record-form.json
- test/fixtures/v3/verifiable-document-form.json
added a utils function for updating of form for v2 and v3.
> feat: added utils function to update form for v2 and v3

- README.md
- package-lock.json
v3 schema in readme is broken, fixing it with new url.
> feat: fix broken v3 schema link

- package-lock.json
- package.json
> fix: bump deps

- package-lock.json
- package.json
- src/2.0/digest.ts
- src/3.0/digest.ts
- update ethers to v5.7.2
- ~~encountering incompatible type warning, changing to spread instead.~~
- ~~what's the [difference](https://stackoverflow.com/a/48866316).~~
- ~~in our case, both arguments are expected arrays, looks like it's fine. do eyeball if this change is ok.~~
- explicitly type `string[]` instead.
> feat: ethers v5 latest

- .husky/commit-msg
- package-lock.json
- package.json
- added pre-commit hook for qol
- lockfile upgraded to v3
> chore: added commitlint precommit hook

- package-lock.json
- package.json
- bump semantic-release to v22
> chore(deps): bump semantic-release

- README.md
In order to update a remote file which retrieves information from this readme, changes are proposed.
- Mainly editing the content
> docs: update readme for the remote file in documentation website

- src/4.0/__tests__/documentBuilder.test.ts
- src/4.0/documentBuilder.ts
- src/4.0/exports/builder.ts
- src/4.0/exports/index.ts
- src/4.0/types.ts
in an attempt to simplify the issuance process via a builder interface:
```typescript
const wrapped = wrapDocument({
"@context": [
"https://www.w3.org/ns/credentials/v2",
"https://schemata.openattestation.com/com/openattestation/4.0/alpha-context.json",
],
type: ["VerifiableCredential", "OpenAttestationCredential"],
validFrom: "2021-03-08T12:00:00+08:00",
name: "Republic of Singapore Driving Licence",
issuer: {
id: "https://example.openattestation.com",
type: "OpenAttestationIssuer",
name: "Government Technology Agency of Singapore (GovTech)",
identityProof: { identityProofType: "DNS-DID", identifier: "example.openattestation.com" },
},
renderMethod: [
{
id: "https://demo-renderer.opencerts.io",
type: "OpenAttestationEmbeddedRenderer",
templateName: "GOVTECH_DEMO",
},
], …
```
> Feat:document builder

- src/3.0/digest.ts
- src/3.0/obfuscate.ts
- src/3.0/salt.ts
- src/3.0/sign.ts
- src/3.0/traverseAndFlatten.ts
- src/3.0/types.ts
- src/3.0/verify.ts
- src/3.0/wrap.ts
- src/index.ts
- src/shared/@types/wrap.ts
Prerequisite to resolve merge conflicts in #297
> fix: mark v3 functions as deprecated in alpha

- README.md
- previous.md
There is a significant change in the way things are done in OA 4.0.
- New readme that focuses on OA 4.0
- Direct users to the old readme if they looking for OA 2.0
> feat: new readme for 4.0

- package-lock.json
- package.json
What is the background of this pull request?
bump dependencies to fix audit issues
- What are the changes made in this pull request?
- Change this and that, etc...
bump quicktype, elliptic and npm
What are the related issues or stories?
> fix: elliptic, cross-spawn audit issues
