- src/schema/3.0/schema.json
- src/schema/3.0/schema.test.ts
- test/e2e.test.ts
* add `W3C-DID` as a supported identityProof type in schema 3.0
* add tests where type: `W3C-DID` and location: `did:ethr:0x...`
> feat: 🎸 add W3C-DID as supported type for issuer identityProof

- src/@types/document.ts
- src/index.ts
- src/schema/2.0/schema.json
- src/schema/2.0/schema.test.ts
- src/schema/3.0/schema.json
- src/schema/3.0/schema.test.ts
- src/schema/3.0/wrapped-sample-document.json
- src/schema/schema.test.ts
- src/utils/utils.test.ts
- src/utils/utils.ts
- test/e2e.v3.test.ts
Updated the schema id `$id`:
- from `open-attestation/2.0` to `https://schema.openattestation.com/2.0/schema.json` 
- from `open-attestation/3.0` to `https://schema.openattestation.com/3.0/schema.json` 
This will make the schema JSON schema compliant so that online JSON schema validator will not complain about the malformed schema and that we will have a permalink to reference the schema in our documentations as well.
Additionally added the long url as enums to the @type/document to prevent lots of copy-pasted urls in the code.
> feat: updated schema id to url

- src/@types/document.ts
- src/digest/digest.test.ts
- src/index.ts
- src/signature/signature.test.ts
This PR introduces stricter types on the `version` string
of the OA document. Random strings will no longer be
accepted. At the same time, the SchemaId is exported to
allow dependencies to use the enum values.
- stricter type on `version`
- exports SchemaId
OA documents using the old version string will be invalidated
> feat: strict schema typing

- src/shared/utils/utils.test.ts
- src/v3/digest/digest.test.ts
- src/v3/schema/sample-document.json
- src/v3/schema/schema.json
- src/v3/schema/schema.test.ts
- test/e2e.v3.test.ts
- Changed type OpenAttestationSignature2018 to OpenAttestationProofMethod
- Created type definition in json schema which can be a string or an array of string
> chore: check on using multiple types in json schema

- src/v3/schema/schema.test.ts
- src/v3/wrap.ts
Since our wrapper adds OA-specific properties, I feel that we should check if the OA v3 context is missing or not. In the original unwrapped document, the user can:
- choose to add in the OA v3 context, then `wrap` will not add it in
- choose not to add in the OA v3 context, then `wrap` will add it in
_(This is also to ensure we can pass the W3C test inputs since the original inputs does not come with OA v3's context)_
This is the logic:
> If `@context` doesn't exist (i.e. `undefined`):
> 
> - `wrap` will create the `@context` array with `https://www.w3.org/2018/credentials/v1` as the first item
> 
> _(Now this would mean that some `@context` validations check in `validateW3C` may be unreachable)_
> 
> Next, if `@context` exists and is an array, and if OA v3 contexts is not in the …
> feat: added w3c context checker in wrap

- src/v3/digest/digest.test.ts
- src/v3/schema/schema.test.ts
- src/v3/wrap.ts
For the digest process:
- Added `illegalCharactersCheck`, to be done before `salt`ing the document
- Checks for `.`, `[` and `]` to prevent such characters from being salted since they would cause shadowed keys
- I didn't put the checks inside `salt` due to how `${path}.${key}` is being recursively passed into `deepMap`
- Fixed the supposed non-deterministic salts, changed it to using hardcoded salts
- Added `number` and `boolean` as allowed data types, and `null` is accepted now
- Allowed data types are: `object, array, string, number, boolean` and values: `null`, everything else is rejected
- Improved test cases expected values
For schema:
- Since `null` is accepted, changed some test cases expected values (should now be expecting schema validation errors)
Also added test case coverage …
> feat: test case coverage for digest, salt

- src/3.0/__tests__/digest.test.ts
Added back the v3 test cases that was removed in https://github.com/Open-Attestation/open-attestation/pull/114/files
Also updated the salts to follow the new salt format
> fix: v3 digest test cases

- src/schema/2.0/sample-document.json
- src/schema/2.0/schema.json
- src/schema/2.0/schema.test.ts
There is a problem attaching files like `.tt` or `.opencert` which gets read as `data:application/octet-stream;base64,ewogICJzY2hlb` with `application/octet-stream` as the type. So... you cannot attach a .tt or .opencert file.
Also, zip files are excluded now. This PR will make the scheme less opinionated.
> feat: allowing any types of attachment

- package-lock.json
- src/2.0/schema/schema.json
- src/3.0/schema/schema.json
this pr does:
- adds more values to the RevocationType enum for v2 and v3
- adds the optional ~~address~~ `location` field in the revocation object
- ~~adds tests for the introduced field.~~
> feat: add support for different revocation types for v2 and v3

- src/shared/utils/utils.ts
- default to throw error if document not match wrapped oa v2 / v3
> fix: throw error get issuer address

- package-lock.json
- package.json
- Update jsonld package to v5.2.0 as it update rdf-canonize dependancy in this version. 
- jsonld v5.2.0 drop node v10 support thus its a breaking change from v4.
- jsonld library did some minor refactoring, dependancies update and clean up from v4 to v5.2.0.
> fix: update jsonld to v5

- package-lock.json
- src/3.0/validate/validate.ts
- because v5's Node.js documentLoader is no longer included in browser build of jsonld, added a condition to fix the loading of the documentLoader.
> fix: node document loader not available in browser

- src/3.0/context/context.jsonld
This PR proposes a way to fix #183. I have introduced new more specific credential type - `OpenAttestationCredential`, and this context only applies to the credential which has this type assigned. So that the credential issuer can override the vocabulary for terms under the `credentialSubject`.
> fixL scoped context under OpenAttestationCredential

- .circleci/config.yml
changed node version from node:latest to node:lts to fix [digital envelope](https://stackoverflow.com/questions/69692842/error0308010cdigital-envelope-routinesunsupported) bug
> fix: 🐛 node version to lts

- README.md
* Removed incorrect example on v3 usage (issue #222 )
* Correct usage now in Additional Information
* fix some typos and grammar
* Mention that docs can also be signed instead of storing the hash on-chain ("did-signed")
>  docs: update README, remove incorrect v3 example

- src/shared/utils/__tests__/utils.test.ts
- src/shared/utils/utils.ts
- test/fixtures/v2/did-signed-ocsp-responder.json
- add check for revocation type `OCSP_RESPONDER` to `isDocumentRevokable` utils.
- v3 [no support](https://github.com/Open-Attestation/oa-verify/blob/master/src/verifiers/documentStatus/didSigned/didSignedDocumentStatus.ts#L266) of `OCSP_RESPONDER` yet, so we omit.
> fix: utils

- src/4.0/schema/schema.json
Remove some required fields from `renderMethod` in order to support SVG rendering
> chore: remove required fields

- src/3.0/digest.ts
`digestCredential()` did not deem falsy values (e.g. `false`, `0`, etc.) as "visible data"
Add an explicit check for `!== undefined` to allow falsy values
> Special thanks to @phanshiyu for highlighting this
> fix: digest should handle falsy values correctly

- package-lock.json
- package.json
- scripts/generateV4JsonSchemas.ts
- src/4.0/jsonSchemas/__generated__/v4-document.schema.json
- src/4.0/jsonSchemas/__generated__/v4-signed-wrapped-document.schema.json
- src/4.0/jsonSchemas/__generated__/v4-wrapped-document.schema.json
- src/index.ts
JSON schemas while inadequate to capture detailed validation logics are still useful for sharing a higher level shape of the document types. 
1. script to generate json schemas from zod
2. generated json schemas for `V4Document`, `V4WrappedDocument` and `V4SignedWrappedDocument`
> chore: generate v4 json schemas based with zod

- src/4.0/__tests__/sign.test.ts
- src/4.0/exports/verify.ts
- src/4.0/sign.ts
its possible for signing to throw errors when network is down, signer or keys are misconfigured
1. Added a new `CouldNotSignDocumentError` and exported it
2. `verify` is now exported as `verifySignature`
> chore: sign document should be clear on what errors it could throw, export of v4 verify shd be more explicit

- src/shared/@types/document.ts
- tsconfig.json
1. es6 is already widely adopted by modern browsers 98% and node v12 and above
2. narrow es2019 to es2019's array method as not all of es2019 is available in modern browsers
3. `baseUrl` is misleading, cos root imports will not work unless there is post processing from something like a bundler
> fix: bump target platform, and remove baseUrl as it is not supported

- src/shared/utils/__tests__/utils.test.ts
- src/shared/utils/index.ts
- src/shared/utils/utils.ts
Hashing utils were being mixed with stuff from other versions, using these utils were forcing v4 specific users to import other things that are not needed
An earlier pr created a dedicated hashing module already.
1. Clean up hashing utils from `utils.ts`
2. Export from `hashing.ts` instead to preserve the utils interface
3. Fix broken references
> fix: clean up hashing utils from utils and fix broken references

- package-lock.json
- package.json
- src/2.0/wrap.ts
- src/3.0/salt.ts
- src/3.0/wrap.ts
- src/4.0/salt.ts
- src/4.0/wrap.ts
- src/shared/merkle/merkle.ts
- src/shared/utils/__tests__/utils.test.ts
- src/shared/utils/hashing.ts
1. remove direct use of crypto and instead use https://www.npmjs.com/package/randombytes, which uses native crypto methods based on environment
2. use https://www.npmjs.com/package/buffer instead of relying on buffer from node env
1. CRA - works out of the box
2. React vite needs 
```
// vite.config.ts
export default defineConfig({
plugins: [react()],
define: {
// By default, Vite doesn't include shims for NodeJS/
// necessary for segment analytics lib to work
global: 'globalThis'
},  
})
```
3. next server side - out of the box
4. next client side - have to install `undici`
> fix: polyfill buffer, shim randombytes

- src/4.0/__tests__/documentBuilder.test.ts
- src/4.0/documentBuilder.ts
1. add an option to not have any rendering method
2. an important svg rendering property were missing, added `digestMultibase`
3. discriminated types for svg, so that with a embedded svg digest is never needed, where remote, user has option to add digest multibase
4. add test
> fix: rendering methods

- package-lock.json
- package.json
- src/4.0/computeDigestMultibase.ts
- src/4.0/exports/utils.ts
Utility to compute digest multibase
```typescript
import { computeDigestMultibase } from "@govtechsg/open-attestation/4.0/utils";
computeDigestMultibase("hello world").then(console.log) // zDULfJyE3WQqNxy3ymuhAChyNR3yufT88pmqvAazKFMG4
```
> feat: digest multibase utility fn

- .lintstagedrc
- package.json
1. not needed to run on each install\
2. scripts break when ran in project that is not of the expected module type
to run script on precommit hook when fixtures.ts changes
> fix: generate fixtures only on change

- src/4.0/__tests__/documentBuilder.test.ts
- src/4.0/__tests__/guard.test.ts
- src/4.0/__tests__/obfuscate.test.ts
- src/4.0/digest.ts
- src/4.0/documentBuilder.ts
- src/4.0/jsonSchemas/__generated__/v4-document.schema.json
- src/4.0/jsonSchemas/__generated__/v4-signed-wrapped-document.schema.json
- src/4.0/jsonSchemas/__generated__/v4-wrapped-document.schema.json
- src/4.0/types.ts
- src/4.0/wrap.ts
- src/shared/@types/document.ts
1. move `attachments` into `credentialSubject`
2. fix typing and test
> fix: v4 attachments

- scripts/generateV4JsonSchemas.ts
- src/4.0/__tests__/e2e.test.ts
- src/4.0/__tests__/guard.test.ts
- src/4.0/__tests__/obfuscate.test.ts
- src/4.0/__tests__/wrap.test.ts
- src/4.0/diagnose.ts
- src/4.0/documentBuilder.ts
- src/4.0/exports/types.ts
- src/4.0/exports/utils.ts
- src/4.0/fixtures.ts
- src/4.0/sign.ts
- src/4.0/types.ts
- src/4.0/wrap.ts
- src/index.ts
- src/shared/@types/document.ts
- src/shared/utils/guard.ts
- src/shared/utils/utils.ts
- src/shared/validate/validate.ts
turns out `Document` isnt great naming
renamed to `OpenAttestationDocument`
> fix: v4 document name

- src/3.0/digest.ts
- src/3.0/obfuscate.ts
- src/3.0/salt.ts
- src/3.0/sign.ts
- src/3.0/traverseAndFlatten.ts
- src/3.0/types.ts
- src/3.0/verify.ts
- src/3.0/wrap.ts
- src/index.ts
- src/shared/@types/wrap.ts
Mark v3 functions as deprecated in favour of the upcoming OpenAttestation v4.0 release
> refactor: mark v3 functions as deprecated

- package-lock.json
- package.json
What is the background of this pull request?
`ajv-formats` is a required production dependency as it is imported in `__generated__/compiled_schema_strict.js`
- What are the changes made in this pull request?
- Change this and that, etc...
`ajv-formats` moved from a dev dependency to a dependency
What are the related issues or stories?
users of the library might experience an error where `ajv-formats` cannot be found
> fix: ajv-formats should be a dependency

- README.md
- package-lock.json
- package.json
- src/2.0/__tests__/sign.test.ts
- src/2.0/sign.ts
- src/3.0/__tests__/sign.test.ts
- src/3.0/sign.ts
- src/index.ts
- src/shared/@types/document.ts
- src/shared/@types/sign.ts
- src/shared/signer/signatureSchemes/Secp256k1VerificationKey2018/Secp256k1VerificationKey2018.ts
- src/shared/signer/signer.ts
- src/shared/utils/diagnose.ts
What is the background of this pull request?
use ether v5 submodules to resolve https://github.com/advisories/GHSA-3h5v-q93c-6h6q
- What are the changes made in this pull request?
- Change this and that, etc...
1. Use only sub modules we need from ethers v5, which does not have the `ws` dependency that is linked to the above mentioned advisory.
What are the related issues or stories?
> fix: ws security advisory from ethers v5 

- src/4.0/__tests__/digest.test.ts
- src/4.0/__tests__/e2e.test.ts
- src/4.0/digest.ts
- src/4.0/sign.ts
We can no longer infer users intention to validate against OA vc data model or the generic w3c VC data model
> fix: allow digesting and signing of modified oa vcs
